<div class="well well-lg hidden" id="family_template___id__">
	<div class="form-group">
		
		<label for="solder_family___id___lname" class="col-sm-1">Прізвище</label>
		<div class="col-sm-2">
			<input type="text" class="form-control" id="solder_family___id___lname" name="solder[family][__id__][lname]" />
		</div>
		
		<label for="solder_family___id___fname" class="col-sm-1">Ім`я</label>
		<div class="col-sm-2">
			<input type="text" class="form-control" id="solder_family___id___fname" name="solder[family][__id__][fname]" />
		</div>
		
		<label for="solder_family___id___sname" class="col-sm-2">По Батькові</label>
		<div class="col-sm-2">
			<input type="text" class="form-control" id="solder_family___id___sname" name="solder[family][__id__][sname]" />
		</div>
		
		<label for="solder_family___id___comment" class="col-sm-1"></label>
		<button type="button" class="btn btn-danger glyphicon glyphicon-minus-sign" id="delete_family___id__"></button>
	</div>
	<div class="form-group">
		<label for="solder_family___id___tel1" class="col-sm-1">Тел1.</label>
		<div class="col-sm-2">
			<input type="tel" class="form-control" id="solder_family___id___tel1" name="solder[family][__id__][tel][1]" />
		</div>
		
		<label for="solder_family___id___tel2" class="col-sm-1">Тел2.</label>
		<div class="col-sm-2">
			<input type="tel" class="form-control" id="solder_family___id___tel2" name="solder[family][__id__][tel][2]" />
		</div>
		
		<label for="solder_family___id___tel3" class="col-sm-2">Тел3.</label>
		<div class="col-sm-2">
			<input type="tel" class="form-control" id="solder_family___id___tel3" name="solder[family][__id__][tel][3]" />
		</div>
	</div>
	<div class="form-group">	
		<label for="solder_family___id___name" class="col-sm-1">Ступінь родства</label>
		<input type="text" class="form-control col-sm-2" id="solder_family___id___name" name="solder[family][__id__][name]" />
		
		<label for="solder_family___id___date" class="col-sm-1">Дата народження</label>
		<input type="date" class="form-control col-sm-2" id="solder_family___id___date" name="solder[family[__id__][date]" />
		
		<label for="solder_family___id___comment" class="col-sm-2">Коментар</label>
		<input type="text" class="form-control col-sm-2" id="solder_family___id___comment" name="solder[family][__id__][comment]" />
	</div>
</div>