<div class="form-group hidden" id="injuries_template___id__">
    <div class="form-group">
        <label for="solder_injuries___id___type" class="col-sm-1">Поранення (діагноз)</label>
        <input type="text" class="form-control col-sm-2" id="solder_injuries___id___name" name="solder[injuries][__id__][name]" />
        <label for="solder_injuries___id___date" class="col-sm-1">Дата отримання</label>
        <input type="date" class="form-control col-sm-2" id="solder_injuries___id___date" name="solder[injuries][__id__][date]" />
        <label for="solder_injuries___id___type" class="col-sm-1">Місце</label>
        <input type="text" class="form-control col-sm-2" id="solder_injuries___id___place" name="solder[injuries][__id__][place]" />
        <label class="col-sm-1"></label>
        <button type="button" class="btn btn-danger glyphicon glyphicon-minus-sign" id="delete_injuries___id__"></button>
    </div>
    <div class="form-group">
        <label for="solder_injuries___id___comment" class="col-sm-1">Коментар</label>
        <input type="text" class="form-control col-sm-8" id="solder_injuries___id___comment" name="solder[injuries][__id__][description]" />
    </div>
</div>