<div class="form-group hidden" id="ranks_template___id__">
    <div class="form-group">
        <label for="solder_ranks___id___type" class="col-sm-1">Звання</label>
        <input type="text" class="form-control col-sm-2" id="solder_ranks___id___name" name="solder[ranks][__id__][name]" />
        <label for="solder_ranks___id___date" class="col-sm-1">Дата присвоєння</label>
        <input type="date" class="form-control col-sm-2" id="solder_ranks___id___date" name="solder[ranks][__id__][date]" />
        <label for="solder_ranks___id___type" class="col-sm-1">Наказ №</label>
        <input type="text" class="form-control col-sm-2" id="solder_ranks___id___order" name="solder[ranks][__id__][order]" />
        <label class="col-sm-1"></label>
        <button type="button" class="btn btn-danger glyphicon glyphicon-minus-sign" id="delete_ranks___id__"></button>
    </div>
    <div class="form-group">
        <label for="solder_ranks___id___comment" class="col-sm-1">Коментар</label>
        <input type="text" class="form-control col-sm-8" id="solder_ranks___id___comment" name="solder[ranks][__id__][description]" />
    </div>
</div>
